backend:
  name: git-gateway
  branch: master

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{title}}/{{year}}-{{month}}-{{day}}_{{title}}_{{some_other_field}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Discription", name: "discription", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
